/** @file

Copyright (c) 2006 - 2011, Byosoft Corporation.<BR> 
All rights reserved.This software and associated documentation (if any)
is furnished under a license and may only be used or copied in 
accordance with the terms of the license. Except as permitted by such
license, no part of this software or documentation may be reproduced, 
stored in a retrieval system, or transmitted in any form or by any 
means without the express written consent of Byosoft Corporation.

File Name:
  SmmStbButtonDispatch2OnSmmStbButtonDispatchThunk.c

Abstract: 
  SMM StandbyButtonDispatch2 Protocol on SMM StandbyButtonDispatch Protocol Thunk driver.

Revision History:
Bug 1920: Create some SMM thunk drivers to support framework style silicon drivers.
TIME: 2011-05-13
$AUTHOR:  Cassie Liu
$REVIEWERS:  Hawker Chen
$SCOPE: Invoke framework implement on EDKII platform.
$TECHNICAL: Produce PI style protocol consuming framework style protocol.
$END----------------------------------------------------------------------------

**/

#include <PiDxe.h>
#include <FrameworkSmm.h>

#include <Protocol/SmmStandbyButtonDispatch2.h>
#include <Protocol/SmmStandbyButtonDispatch.h>
#include <Library/UefiBootServicesTableLib.h>
#include <Library/UefiDriverEntryPoint.h>
#include <Library/SmmServicesTableLib.h>
#include <Library/DebugLib.h>

/**
  Register a child SMI source dispatch function for the specified Standby Button SMI.

  This service registers a function (DispatchFunction) which will be called when the Standby Button 
  SMI source is detected. On return, 
  DispatchHandle contains a unique handle which may be used later to unregister the function 
  using UnRegister().

  @param[in]  This                  Pointer to the EFI_SMM_STANDBY_BUTTON_DISPATCH2_PROTOCOL instance.
  @param[in]  DispatchFunction      Function to register for handler when the Standby Button
                                    SMI is generated. 
  @param[in, out]  RegisterContext  Pointer to the dispatch function's context.
                                    The caller fills this context in before calling
                                    the register function to indicate to the register
                                    function which Standby Button phase the
                                    dispatch function should be invoked for.
  @param[out] DispatchHandle        Handle generated by the dispatcher to track the
                                    function instance.

  @retval EFI_SUCCESS               The dispatch function has been successfully
                                    registered and the SMI source has been enabled.
  @retval EFI_DEVICE_ERROR          The Standby Button driver was unable to enable the SMI source.
  @retval EFI_INVALID_PARAMETER     RegisterContext is invalid. The SMI Standby Button phase
                                    is not within valid range.
  @retval EFI_OUT_OF_RESOURCES      There is not enough memory (system or SMM) to manage this
                                    child.
  @retval EFI_OUT_OF_RESOURCES      The Standby Button SMI could not be assigned
                                    for this dispatch.
**/
EFI_STATUS
EFIAPI
SmmStandbyButtonDispatch2Register (
  IN  CONST EFI_SMM_STANDBY_BUTTON_DISPATCH2_PROTOCOL  *This,
  IN        EFI_SMM_HANDLER_ENTRY_POINT2               DispatchFunction,
  IN  CONST EFI_SMM_STANDBY_BUTTON_REGISTER_CONTEXT    *RegisterContext,
  OUT       EFI_HANDLE                                 *DispatchHandle
  );

/**
  Unregister a child SMI source dispatch function for the Standby Button SMI.

  This service removes the handler associated with DispatchHandle so that it will no longer be 
  called in response to a Standby Button SMI.

  @param[in] This                Pointer to the EFI_SMM_STANDBY_BUTTON_DISPATCH2_PROTOCOL instance.
  @param[in] DispatchHandle      Handle of dispatch function to deregister.

  @retval EFI_SUCCESS            The dispatch function has been successfully unregistered.
  @retval EFI_INVALID_PARAMETER  The DispatchHandle was not valid.
**/
EFI_STATUS
EFIAPI
SmmStandbyButtonDispatch2UnRegister (
  IN CONST EFI_SMM_STANDBY_BUTTON_DISPATCH2_PROTOCOL  *This,
  IN       EFI_HANDLE                                 DispatchHandle
  );
  

EFI_SMM_STANDBY_BUTTON_DISPATCH2_PROTOCOL gSmmStandbyButtonDispatch2 = {
  SmmStandbyButtonDispatch2Register,
  SmmStandbyButtonDispatch2UnRegister
};

EFI_SMM_STANDBY_BUTTON_DISPATCH_PROTOCOL  *mSmmStandbyButtonDispatch;

/**
  Register a child SMI source dispatch function for the specified Standby Button SMI.

  This service registers a function (DispatchFunction) which will be called when the Standby Button 
  SMI source is detected. On return, 
  DispatchHandle contains a unique handle which may be used later to unregister the function 
  using UnRegister().

  @param[in]  This                  Pointer to the EFI_SMM_STANDBY_BUTTON_DISPATCH2_PROTOCOL instance.
  @param[in]  DispatchFunction      Function to register for handler when the Standby Button
                                    SMI is generated. 
  @param[in, out]  RegisterContext  Pointer to the dispatch function's context.
                                    The caller fills this context in before calling
                                    the register function to indicate to the register
                                    function which Standby Button phase the
                                    dispatch function should be invoked for.
  @param[out] DispatchHandle        Handle generated by the dispatcher to track the
                                    function instance.

  @retval EFI_SUCCESS               The dispatch function has been successfully
                                    registered and the SMI source has been enabled.
  @retval EFI_DEVICE_ERROR          The Standby Button driver was unable to enable the SMI source.
  @retval EFI_INVALID_PARAMETER     RegisterContext is invalid. The SMI Standby Button phase
                                    is not within valid range.
  @retval EFI_OUT_OF_RESOURCES      There is not enough memory (system or SMM) to manage this
                                    child.
  @retval EFI_OUT_OF_RESOURCES      The Standby Button SMI could not be assigned
                                    for this dispatch.
**/
EFI_STATUS
EFIAPI
SmmStandbyButtonDispatch2Register (
  IN  CONST EFI_SMM_STANDBY_BUTTON_DISPATCH2_PROTOCOL  *This,
  IN        EFI_SMM_HANDLER_ENTRY_POINT2               DispatchFunction,
  IN  CONST EFI_SMM_STANDBY_BUTTON_REGISTER_CONTEXT    *RegisterContext,
  OUT       EFI_HANDLE                                 *DispatchHandle
  )
{
  EFI_STATUS                            Status;

  Status = mSmmStandbyButtonDispatch->Register (
                                        mSmmStandbyButtonDispatch,
                                        (EFI_SMM_STANDBY_BUTTON_DISPATCH) DispatchFunction,
                                        (EFI_SMM_STANDBY_BUTTON_DISPATCH_CONTEXT *) RegisterContext,
                                        DispatchHandle
                                        );
  return Status;
}

/**
  Unregister a child SMI source dispatch function for the specified standby button SMI.

  This service removes the handler associated with DispatchHandle so that it will no longer be 
  called in response to a standby button SMI.

  @param[in] This                Pointer to the EFI_SMM_STANDBY_BUTTON_DISPATCH2_PROTOCOL instance.
  @param[in] DispatchHandle      Handle of dispatch function to deregister.

  @retval EFI_SUCCESS            The dispatch function has been successfully unregistered.
  @retval EFI_INVALID_PARAMETER  The DispatchHandle was not valid.
**/
EFI_STATUS
EFIAPI
SmmStandbyButtonDispatch2UnRegister (
  IN CONST EFI_SMM_STANDBY_BUTTON_DISPATCH2_PROTOCOL  *This,
  IN       EFI_HANDLE                                 DispatchHandle
  )
{
  EFI_STATUS                            Status;

  Status = mSmmStandbyButtonDispatch->UnRegister (mSmmStandbyButtonDispatch, DispatchHandle);
  
  return Status;
}

/**
  Entry Point for this thunk driver.

  @param[in] ImageHandle  Image handle of this driver.
  @param[in] SystemTable  A Pointer to the EFI System Table.

  @retval EFI_SUCCESS     The entry point is executed successfully.
  @retval other           Some error occurred when executing this entry point.
**/
EFI_STATUS
EFIAPI
SmmStandbyButtonDispatch2ThunkMain (
  IN EFI_HANDLE        ImageHandle,
  IN EFI_SYSTEM_TABLE  *SystemTable
  )
{
  EFI_STATUS               Status;

  ///
  /// Locate Framework SMM StandbyButtonDispatch Protocol
  ///
  Status = gBS->LocateProtocol (
                  &gEfiSmmStandbyButtonDispatchProtocolGuid,
                  NULL, (VOID **)&mSmmStandbyButtonDispatch
                  );
  ASSERT_EFI_ERROR (Status);

  ///
  /// Publish PI SMM StandbyButtonDispatch2 Protocol
  ///
  ImageHandle = NULL;
  Status = gSmst->SmmInstallProtocolInterface (
                    &ImageHandle,
                    &gEfiSmmStandbyButtonDispatch2ProtocolGuid,
                    EFI_NATIVE_INTERFACE,
                    &gSmmStandbyButtonDispatch2
                    );
  ASSERT_EFI_ERROR (Status);
  return Status;
}

