/** @file

Copyright (c) 2006 - 2011, Byosoft Corporation.<BR> 
All rights reserved.This software and associated documentation (if any)
is furnished under a license and may only be used or copied in 
accordance with the terms of the license. Except as permitted by such
license, no part of this software or documentation may be reproduced, 
stored in a retrieval system, or transmitted in any form or by any 
means without the express written consent of Byosoft Corporation.

File Name:
  SmmPerTimerDispatch2OnSmmPerTimerDispatchThunk.c

Abstract: 
  SMM PeriodicTimerDispatch2 Protocol on SMM PeriodicTimerDispatch Protocol Thunk driver.

Revision History:
Bug 1920: Create some SMM thunk drivers to support framework style silicon drivers.
TIME: 2011-05-13
$AUTHOR:  Cassie Liu
$REVIEWERS:  Hawker Chen
$SCOPE: Invoke framework implement on EDKII platform.
$TECHNICAL: Produce PI style protocol consuming framework style protocol.
$END----------------------------------------------------------------------------

**/

#include <PiDxe.h>
#include <FrameworkSmm.h>

#include <Protocol/SmmPeriodicTimerDispatch2.h>
#include <Protocol/SmmPeriodicTimerDispatch.h>
#include <Protocol/SmmControl.h>
#include <Protocol/SmmCpu.h>
#include <Library/UefiBootServicesTableLib.h>
#include <Library/UefiDriverEntryPoint.h>
#include <Library/SmmServicesTableLib.h>
#include <Library/BaseLib.h>
#include <Library/IoLib.h>
#include <Library/DebugLib.h>


/**
  Register a child SMI source dispatch function for the specified Periodic Timer SMI.

  This service registers a function (DispatchFunction) which will be called when the periodic timer 
  SMI source specified is detected. On return, 
  DispatchHandle contains a unique handle which may be used later to unregister the function 
  using UnRegister().

  @param[in]  This                  Pointer to the EFI_SMM_PERIODIC_TIMER_DISPATCH2_PROTOCOL instance.
  @param[in]  DispatchFunction      Function to register for handler when the specified periodic tiemr 
                                    SMI is generated. 
  @param[in, out]  RegisterContext  Pointer to the dispatch function's context.
                                    The caller fills this context in before calling
                                    the register function to indicate to the register
                                    function which the minimum of time and interval for periodic timer SMI
                                    the dispatch function should be invoked for.
  @param[out] DispatchHandle        Handle generated by the dispatcher to track the
                                    function instance.

  @retval EFI_SUCCESS               The dispatch function has been successfully
                                    registered and the SMI source has been enabled.
  @retval EFI_DEVICE_ERROR          The periodic tiemr driver was unable to enable the SMI source.
  @retval EFI_INVALID_PARAMETER     RegisterContext is invalid. 
  @retval EFI_OUT_OF_RESOURCES      There is not enough memory (system or SMM) to manage this child.
  @retval EFI_OUT_OF_RESOURCES      A unique periodic tiemr SMI could not be assigned
                                    for this dispatch.
**/
EFI_STATUS
EFIAPI
SmmPeriodicTimerDispatch2Register (
  IN  CONST EFI_SMM_PERIODIC_TIMER_DISPATCH2_PROTOCOL  *This,
  IN        EFI_SMM_HANDLER_ENTRY_POINT2               DispatchFunction,
  IN  CONST EFI_SMM_PERIODIC_TIMER_REGISTER_CONTEXT    *RegisterContext,
  OUT       EFI_HANDLE                                 *DispatchHandle
  );


/**
  Unregister a child SMI source dispatch function for the periodic timer SMI.

  This service removes the handler associated with DispatchHandle so that it will no longer be 
  called in response to a periodic timer SMI.

  @param[in] This                Pointer to the EFI_SMM_PERIODIC_TIMER_DISPATCH2_PROTOCOL instance.
  @param[in] DispatchHandle      Handle of dispatch function to deregister.

  @retval EFI_SUCCESS            The dispatch function has been successfully unregistered.
  @retval EFI_INVALID_PARAMETER  The DispatchHandle was not valid.
**/
EFI_STATUS
EFIAPI
SmmPeriodicTimerDispatch2UnRegister (
  IN CONST EFI_SMM_PERIODIC_TIMER_DISPATCH2_PROTOCOL  *This,
  IN       EFI_HANDLE                                 DispatchHandle
  );

/**
  Get next SMI tick period dispatch function for the periodic timer SMI.

  This service returns the next SMI tick period that is supported by the chipset.
  The order returned is from longest to shortest interval period.

  @param[in] This                Pointer to the EFI_SMM_PERIODIC_TIMER_DISPATCH2_PROTOCOL instance.
  @param[in] SmiTickInterval     Pointer to pointer of the next shorter SMI 
                                 interval period that is supported by the child.

  @retval EFI_SUCCESS            The service returned successfully.
  @retval EFI_INVALID_PARAMETER  The parameter SmiTickInterval is invalid.
**/
EFI_STATUS
EFIAPI
SmmPeriodicTimerDispatch2GetNextShorterInterval (
  IN CONST EFI_SMM_PERIODIC_TIMER_DISPATCH2_PROTOCOL  *This,
  IN OUT   UINT64                                     **SmiTickInterval
  );


EFI_SMM_PERIODIC_TIMER_DISPATCH2_PROTOCOL gSmmPeriodicTimerDispatch2 = {
  SmmPeriodicTimerDispatch2Register,
  SmmPeriodicTimerDispatch2UnRegister,
  SmmPeriodicTimerDispatch2GetNextShorterInterval
};

EFI_SMM_PERIODIC_TIMER_DISPATCH_PROTOCOL  *mSmmPeriodicTimerDispatch;


/**
  Register a child SMI source dispatch function for the specified Periodic Timer SMI.

  This service registers a function (DispatchFunction) which will be called when the periodic timer 
  SMI source specified is detected. On return, 
  DispatchHandle contains a unique handle which may be used later to unregister the function 
  using UnRegister().

  @param[in]  This                  Pointer to the EFI_SMM_PERIODIC_TIMER_DISPATCH2_PROTOCOL instance.
  @param[in]  DispatchFunction      Function to register for handler when the specified periodic tiemr 
                                    SMI is generated. 
  @param[in, out]  RegisterContext  Pointer to the dispatch function's context.
                                    The caller fills this context in before calling
                                    the register function to indicate to the register
                                    function which the minimum of time and interval for periodic timer SMI
                                    the dispatch function should be invoked for.
  @param[out] DispatchHandle        Handle generated by the dispatcher to track the
                                    function instance.

  @retval EFI_SUCCESS               The dispatch function has been successfully
                                    registered and the SMI source has been enabled.
  @retval EFI_DEVICE_ERROR          The periodic tiemr driver was unable to enable the SMI source.
  @retval EFI_INVALID_PARAMETER     RegisterContext is invalid. 
  @retval EFI_OUT_OF_RESOURCES      There is not enough memory (system or SMM) to manage this child.
  @retval EFI_OUT_OF_RESOURCES      A unique periodic tiemr SMI could not be assigned
                                    for this dispatch.
**/
EFI_STATUS
EFIAPI
SmmPeriodicTimerDispatch2Register (
  IN  CONST EFI_SMM_PERIODIC_TIMER_DISPATCH2_PROTOCOL  *This,
  IN        EFI_SMM_HANDLER_ENTRY_POINT2               DispatchFunction,
  IN  CONST EFI_SMM_PERIODIC_TIMER_REGISTER_CONTEXT    *RegisterContext,
  OUT       EFI_HANDLE                                 *DispatchHandle
  )
{
  EFI_STATUS                            Status;

  Status = mSmmPeriodicTimerDispatch->Register (
                                        mSmmPeriodicTimerDispatch,
                                        (EFI_SMM_PERIODIC_TIMER_DISPATCH) DispatchFunction,
                                        (EFI_SMM_PERIODIC_TIMER_DISPATCH_CONTEXT *) RegisterContext,
                                        DispatchHandle
                                        );

  return Status;
}

/**
  Unregister a child SMI source dispatch function for the periodic timer SMI.

  This service removes the handler associated with DispatchHandle so that it will no longer be 
  called in response to a periodic timer SMI.

  @param[in] This                Pointer to the EFI_SMM_PERIODIC_TIMER_DISPATCH2_PROTOCOL instance.
  @param[in] DispatchHandle      Handle of dispatch function to deregister.

  @retval EFI_SUCCESS            The dispatch function has been successfully unregistered.
  @retval EFI_INVALID_PARAMETER  The DispatchHandle was not valid.
**/
EFI_STATUS
EFIAPI
SmmPeriodicTimerDispatch2UnRegister (
  IN CONST EFI_SMM_PERIODIC_TIMER_DISPATCH2_PROTOCOL  *This,
  IN       EFI_HANDLE                                 DispatchHandle
  )
{
  EFI_STATUS                            Status;

  Status = mSmmPeriodicTimerDispatch->UnRegister (mSmmPeriodicTimerDispatch, DispatchHandle);
  
  return Status;
}

/**
  Get next SMI tick period dispatch function for the periodic timer SMI.

  This service returns the next SMI tick period that is supported by the chipset.
  The order returned is from longest to shortest interval period.

  @param[in] This                Pointer to the EFI_SMM_PERIODIC_TIMER_DISPATCH2_PROTOCOL instance.
  @param[in] SmiTickInterval     Pointer to pointer of the next shorter SMI 
                                 interval period that is supported by the child.

  @retval EFI_SUCCESS            The service returned successfully.
  @retval EFI_INVALID_PARAMETER  The parameter SmiTickInterval is invalid.
**/
EFI_STATUS
EFIAPI
SmmPeriodicTimerDispatch2GetNextShorterInterval (
  IN CONST EFI_SMM_PERIODIC_TIMER_DISPATCH2_PROTOCOL  *This,
  IN OUT   UINT64                                     **SmiTickInterval
  )
{
  EFI_STATUS                            Status;

  Status = mSmmPeriodicTimerDispatch->GetNextShorterInterval (mSmmPeriodicTimerDispatch, SmiTickInterval);
  
  return Status;
}

/**
  Entry Point for this thunk driver.

  @param[in] ImageHandle  Image handle of this driver.
  @param[in] SystemTable  A Pointer to the EFI System Table.

  @retval EFI_SUCCESS     The entry point is executed successfully.
  @retval other           Some error occurred when executing this entry point.
**/
EFI_STATUS
EFIAPI
SmmPeriodicTimerDispatch2ThunkMain (
  IN EFI_HANDLE        ImageHandle,
  IN EFI_SYSTEM_TABLE  *SystemTable
  )
{
  EFI_STATUS               Status;

  ///
  /// Locate Framework SMM PeriodicTimerDispatch Protocol
  ///
  Status = gBS->LocateProtocol (&gEfiSmmPeriodicTimerDispatchProtocolGuid, NULL, (VOID **)&mSmmPeriodicTimerDispatch);
  ASSERT_EFI_ERROR (Status);
  
  ///
  /// Publish PI SMM PeriodicTimerDispatch2 Protocol
  ///
  ImageHandle = NULL;
  Status = gSmst->SmmInstallProtocolInterface (
                    &ImageHandle,
                    &gEfiSmmPeriodicTimerDispatch2ProtocolGuid,
                    EFI_NATIVE_INTERFACE,
                    &gSmmPeriodicTimerDispatch2
                    );
  ASSERT_EFI_ERROR (Status);
  return Status;
}

